spring:
  application:
    name: async-adapter-demo
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: "myGroup"
      bootstrap-servers: localhost:9092
    producer:
      value-serializer: org.apache.kafka.common.serialization.DoubleSerializer
  datasource:
    driver-class-name: org.postgresql.Driver
    username: app
    password: pass
    url: jdbc:postgresql://localhost:5432/async_adapter