spring:
  application:
    name: async-adapter-demo
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: "myGroup"
      bootstrap-servers: localhost:9092
      auto-offset-reset: earliest
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
  datasource:
    driver-class-name: org.postgresql.Driver
    username: app
    password: pass
    url: jdbc:postgresql://localhost:5432/async_adapter
  jpa:
    properties:
      hibernate.default_schema: async_adapter
  sql:
    init:
      mode: always