spring:
  application:
    name: async-adapter-demo
  kafka:
    bootstrap-servers: "localhost:9092"
    consumer:
      group-id: "myGroup"
      value-deserializer: "org.springframework.kafka.support.serializer.StringDeserializer"
    producer:
      value-serializer: "org.springframework.kafka.support.serializer.DoubleSerializer"
  datasource:
    driver-class-name: org.postgresql.Driver
    username: app
    password: pass
    url: jdbc:postgresql://localhost:5432/async_adapter